export const COMMONJS_POLYFILLS_BANNER = `
// CommonJS polyfills generated by the TypeStream for compatibility with CommonJS
// modules which depend on CommonJS-specific Node.js globals to work
import { createRequire as __cjspCreateRequire } from 'node:module';
const require = __cjspCreateRequire(import.meta.url);

import { dirname as __cjspDirname } from 'node:path';
import { fileURLToPath as __cjspFileURLToPath } from 'node:url';
const __dirname = __cjspDirname(__cjspFileURLToPath(import.meta.url));

// Start of the regular bundle
`.trim()
